spring:
  application:
    name: cnd-lea-member

logging:
  file:
    name: logs/lea-member.log
  level:
    root: INFO
    com.fusionsoft: debug
    jdbc:
      resultsettable: INFO
      sqltiming: OFF
      sqlonly: INFO
      audit: OFF
      resultset: OFF
      connection: OFF
    net:
      sf:
        log4jdbc: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8082