spring:
  application:
    name: cnd-com-auth

  data:
    redis:

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/prj-db?CharacterEncoding=UTF-8
    username: viaura
    password: money

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  sql:
    init:
      mode: always

jwt:
  secret: FusionsoftCndProjectSecretKey0123456789
  access-token-validity-seconds: 900    # 15 minutes
  refresh-token-validity-seconds: 1209600 # 14 days

logging:
  file:
    name: logs/auth.log
  level:
    root: INFO
    jdbc:
      resultsettable: INFO
      sqltiming: OFF
      sqlonly: OFF
      audit: OFF
      resultset: OFF
      connection: OFF
    net:
      sf:
        log4jdbc: WARN