apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: cnd-dev
type: Opaque
stringData:
  jwt.secret: "RnVzaW9uc29mdENuZFByb2plY3RTZWNyZXRLZXlQbGVhc2VDYWxsRnVzaW9uU29mdCs4MjUzNjA5NzM1Mw=="
  jwt.access-token-validity-seconds: "1209600"
  jwt.refresh-token-validity-seconds: "2592000"
