---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnd-com-api-gateway
  namespace: cnd-dev
  labels:
    app: cnd-com-api-gateway
    app.kubernetes.io/name: api-gateway
    project: cnd-com          # <- 프로젝트 단위 라벨 추가
    environment: dev          # <- 환경 구분 라벨
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnd-com-api-gateway
      project: cnd-com          # <- 프로젝트 단위 라벨 추가
      environment: dev          # <- 환경 구분 라벨
  template:
    metadata:
      labels:
        app: cnd-com-api-gateway
        app.kubernetes.io/name: api-gateway
        project: cnd-com          # <- 프로젝트 단위 라벨 추가
        environment: dev          # <- 환경 구분 라벨
    spec:
      containers:
        - name: cnd-com-api-gateway
          image: cnd/cnd-com-api-gateway:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            # Spring Profile 활성화
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            # JWT Secret (Secret에서 주입)
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                    name: jwt-secret
                    key: jwt.secret
            - name: JWT_ACCESS_TOKEN_VALIDITY
              valueFrom:
                 secretKeyRef:
                    name: jwt-secret
                    key: jwt.access-token-validity-seconds
            - name: JWT_REFRESH_TOKEN_VALIDITY
              valueFrom:
                 secretKeyRef:
                    name: jwt-secret
                    key: jwt.refresh-token-validity-seconds

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: cnd-dev
  labels:
    app: api-gateway
    app.kubernetes.io/name: api-gateway
    project: cnd-com        # 프로젝트 라벨 추가 가능
spec:
  selector:
    app: cnd-com-api-gateway
    project: cnd-com        # Pod template에 있는 라벨과 일치해야 선택됨
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080