apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-auth-endpoints
  namespace: cnd-dev
spec:
  selector:
    matchLabels:
      app: api-gateway
  action: ALLOW
  rules:
    - to:
        - operation:
            paths:
              - "/api/auth/login"
              - "/api/auth/register"
              - "/api/auth/logout"
