# version: '3.9'
name: cnd

networks:
  frontend:
    name: frontend-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.2.0/24
  backend:
    name: backend-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.3.0/24
  db:
    name: db-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.4.0/24
          gateway: 172.19.4.1
  manage:
    name: manage-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.5.0/24
          gateway: 172.19.5.1


services:
  db-master:
    image: mariadb:10.6.23-ubi9
    #user: "1001"
    restart: always
    hostname: mariadb-master
    environment:
      # https://mariadb.com/kb/en/mariadb-server-docker-official-image-environment-variables
      TZ: Asia/Seoul
      MARIADB_ROOT_PASSWORD: aprkwhs
      MARIADB_DATABASE: cnd
      MARIADB_USER: viaura
      MARIADB_PASSWORD: money
      MARIADB_REPLICATION_USER: replica_user
      MARIADB_REPLICATION_PASSWORD: money
    command:
      - --server-id=1
      - --log-basename=master
      - --expire-logs-days=10
      - --log-bin=mariadb-bin
    ports:
      - 3306:3306
    container_name: mariadb-master
    volumes:
      - mariadb_master_volume:/var/lib/mysql
      - ./mariadb.cnf:/etc/my.cnf.d/mariadb.cnf:ro
      - ./init-gitea.sql:/docker-entrypoint-initdb.d/init-gitea.sql:ro
      - ./init-redmine.sql:/docker-entrypoint-initdb.d/init-redmine.sql:ro
      - ./init-mattermost.sql:/docker-entrypoint-initdb.d/init-mattermost.sql:ro
    healthcheck:
      test: ['CMD', '/usr/local/bin/healthcheck.sh', '--innodb_initialized']
      start_period: 5s
      timeout: 5s
      interval: 10s
      retries: 5

    networks:
      db:
        ipv4_address: 172.19.4.2

  db-slave01:
    image: mariadb:10.6.23-ubi9
    #user: "1001"
    restart: always
    hostname: mariadb-slave01
    environment:
      # https://mariadb.com/kb/en/mariadb-server-docker-official-image-environment-variables
      TZ: Asia/Seoul
      MARIADB_ROOT_PASSWORD: aprkwhs
      # slave는 master 에서 생기는 대로 리플리케이션 되므로 DB, USER 등등 세팅이 불필요하다
      #MARIADB_DATABASE: danchoo_plus
      #MARIADB_USER: viaura
      #MARIADB_PASSWORD: money
      MARIADB_MASTER_HOST: mariadb-master
      MARIADB_REPLICATION_USER: replica_user
      MARIADB_REPLICATION_PASSWORD: money
      MARIADB_HEALTHCHECK_GRANTS:
    command:
      - --server-id=2
      - --log-basename=slave01
    ports:
      - 3307:3306
    container_name: mariadb-slave01
    volumes:
      - mariadb_slave01_volume:/var/lib/mysql
      - ./mariadb.cnf:/etc/my.cnf.d/mariadb.cnf
    healthcheck:
      test: ['CMD', '/usr/local/bin/healthcheck.sh', '--innodb_initialized']
      start_period: 5s
      timeout: 5s
      interval: 10s
      retries: 5

    networks:
      db:
        ipv4_address: 172.19.4.3

volumes:
  mariadb_master_volume:
  mariadb_slave01_volume: