spring:
  application:
    name: cnd-com-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: member-service
              uri: http://member-service.cnd-dev.svc.cluster.local:80
              predicates:
                - Path=/api/members/v1/**
#              filters:
#                - StripPrefix=1

            - id: reserve-service
              uri: http://reserve-service.cnd-dev.svc.cluster.local:8080
              predicates:
                - Path=/api/reserves/v1/**
#              filters:
#                - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info