spring:
  application:
    name: cnd-com-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: member-service
              uri: http://member-service.cnd-dev.svc.cluster.local:80
              predicates:
                - Path=/api/members/v1/**
            - id: reserve-service
              uri: http://reserve-service.cnd-dev.svc.cluster.local:80
              predicates:
                - Path=/api/reserves/v1/**
            - id: auth-service
              uri: http://auth-service.cnd-dev.svc.cluster.local:80
              predicates:
                - Path=/api/auth/**
                - Path=/api/test/**


jwt:
  #SecretKeyGenerator 로 생성, Base64 encoded
  secret: ${JWT_SECRET}
  access-token-validity-seconds: ${JWT_ACCESS_TOKEN_VALIDITY:1209600}  # 14 days
  refresh-token-validity-seconds: ${JWT_REFRESH_TOKEN_VALIDITY:2592000} # 30 days

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  file:
    name: logs/api-gateway.log
  level:
    root: INFO
    com.fusionsoft: debug
